# Generated by Django 2.2.3 on 2019-07-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
                ('parent_id', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=30)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=30)),
            ],
        ),
    ]
